/* ============================================================
   Mix for a Mission — product-data.js
   A single product data object covering every item across all
   five menu categories. Keyed by "category-flavor-slug" (e.g.
   "cake-black-forest", "cupcake-black-forest") so the same
   flavor name across categories doesn't collide.

   Ten items (6 cakes, 4 cupcakes) have real tagline/ingredients/
   sizeInfo data sourced from the old Google Sites product pages.
   All other entries have those fields as empty
   strings — the template handles the fallback display.

   Load this BEFORE main.js on pages that need it.
   ============================================================ */

var productData = {
  /* ======================================================
     CAKES — 23 items
     ====================================================== */
  "cake-almond-crunch-bar": {
    name: "Almond Crunch Bar Cake",
    category: "cake",
    tagline: "Inspired by classic almond ice cream bars. Delicate almond flavor with a crunchy almond roast, smooth buttercream that's not too sweet. If you like almonds, this is your cake.",
    ingredients: "VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE)), WATER, SALT, NATURAL FLAVOR (DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR), SUGAR, SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), ALMONDS, POWDERED SUGAR, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), WATER, FLAXSEED, APPLE CIDER VINEGAR, ALMOND EXTRACT (WATER, ALCOHOL, OIL OF BITTER ALMOND), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT",
    sizeInfo: "Net weight: 90 oz (2551g)",
    gfAvailable: false,
    imageKey: "almond",
    allergens: "ALMOND, WHEAT, SOY",
  },

  "cake-chocolate-vanilla-buttercream": {
    name: "Chocolate Cake w/Vanilla Buttercream",
    category: "cake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "chocolate",
    allergens: "",
  },
  "cake-chocolate-mint": {
    name: "Chocolate Mint Cake",
    category: "cake",
    tagline: "Cool peppermint and dark chocolate in three layers. Refreshing and rich. People order this one all year, not just around the holidays.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), GEL FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, YELLOW 5, CARRAGEENAN, BLUE 1, RED 40, SODIUM BENZOATE (PRESERVATIVE), CIRTRIC ACID, BAKING POWDER (CORN STARCH, SODIUM BICARBONATE, SODIUM ALUMINUM SULFATE, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "Net weight: 77.60oz (2200g)",
    gfAvailable: true,
    imageKey: "mint",
    allergens: "WHEAT, SOY",
  },
  "cake-enchanted-tree-stump": {
    name: "Enchanted Tree Stump Cake (+$5)",
    category: "cake",
    tagline: "A whimsical chocolate creation disguised as a forest tree stump — complete with meringue mushrooms, chocolate bark, and a mossy matcha dusting. Almost too magical to eat. Almost.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, SEMI-SWEET CHOCOLATE CHIPS (CHOCOLATE LIQUOR, SUGAR, SOY LECITHIN, VANILLA), POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), AQUAFABA, COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), WATER, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), INSTANT COFFEE POWDER, SALT, MATCHA POWDER",
    sizeInfo: "Net weight: 91.71oz (2600g)",
    gfAvailable: true,
    imageKey: "chocolate",
    allergens: "WHEAT, SOY",
  },
  "cake-chocolate-oreo-crunch": {
    name: "Chocolate Oreo Crunch Cake",
    category: "cake",
    tagline: "Cookies-and-cream, but make it a cake. Three chocolate layers loaded with Oreo crunch and smooth buttercream — a crowd favorite that sells out fast.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, SEMISWEET CHOCOLATE CHIPS (CHOCOLATE LIQUOR, SUGAR, SOY LECITHIN, VANILLA), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, REDSODIUM BENZOATE (PRESERVATIVE), CITRIC ACID), BAKING POWDER (CORN STARCH, SODIUM BICARBONATE, SODIUM ALUMINUM SULFATE, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "Net weight: 84.66oz (2400g)",
    gfAvailable: false,
    imageKey: "oreo",
    allergens: "WHEAT, SOY",
  },
  "cake-chocolate-strawberry-crunch": {
    name: "Chocolate Strawberry Crunch Cake",
    category: "cake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "strawberry",
    allergens: "",
  },
  "cake-chocolate-caramel-peanut-butter": {
    name: "Chocolate Caramel Peanut Butter Cake",
    category: "cake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "peanut",
    allergens: "",
  },
  "cake-black-forest": {
    name: "Black Forest Cake",
    category: "cake",
    tagline: "A vegan chocolate cake decorated to look like a forest. Meringue mushrooms, chocolate bark, matcha moss. It's the cake people send us the most messages about.",
    ingredients: "Chocolate cake (enriched flour (wheat flour, niacin, reduced iron, thiamine, mononitrate, riboflavin, folic acid), organic sugar, water, organic soymilk (filtered water, organic soybeans, contains 2% or less of: vitamin and mineral blend (calcium carbonate, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sea salt, gellan gum, ascorbic acid (vitamin C to protect)), canola oil, cocoa (processed with alkali), instant coffee powder, baking powder, baking soda, vanilla extract (water, ethyl alcohol, vanilla extract)); buttercream (vegan butter (vegetable oil blend (palm oil, canola oil), water, salt, pea protein isolate, monoglycerides, diglycerides, sunflower lecithin, artificial flavors, vitamin A palmitate, beta carotene with potassium sorbate, lactic acid, and calcium disodium EDTA), shortening (canola oil, modified palm and palm kernel oils, mono and diglycerides), corn syrup (light corn syrup, salt, and vanilla), sugar, water, instant coffee powder, vanilla extract (water, ethyl alcohol, vanilla extract), chocolate shards (sugar, hydrogenated palm fat, cocoa, soy lecithin, flavorings), meringue mushrooms (aquafaba, organic sugar, vinegar, cocoa powder (processed with alkali), matcha powder)).",
    sizeInfo: "3 layers, 7-inch diameter, serves 10\u201315",
    gfAvailable: true,
    imageKey: "blackforest",
    allergens: ""
  },
  "cake-vanilla-sprinkles": {
    name: "Vanilla Sprinkles Cake",
    category: "cake",
    tagline: "A classic vanilla cake loaded with rainbow sprinkles. Fun, colorful, and always the first one finished at a party.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), RAINBOW SPRINKLES (SUGAR, HYDROGENATED PALM KERNEL OIL, CORN STARCH, SUNFLOWER LECITHIN, FD&C COLORS YELLOW 6 LAKE, YELLOW 5 LAKE, BLUE 1 LAKE, RED 40 LAKE, RED 3, MALTODEXTRIN, CARNAUBA WAX, VANILLIN, CELLULOSE GUM), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 84.66oz (2400g)",
    gfAvailable: true,
    imageKey: "vanilla",
    allergens: "WHEAT, SOY",
  },
  "cake-vanilla-coconut": {
    name: "Vanilla Coconut Cake",
    category: "cake",
    tagline: "Vanilla cake with real coconut flakes and coconut extract. Tropical without being fake about it.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), UNSWEETENED COCONUT FLAKES, APPLE CIDER VINEGAR, COCONUT EXTRACT (ALCHOL, WATER, GLYCERIN, AND NATURAL COCONUT FLAVORS), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 90oz (2551g)",
    gfAvailable: true,
    imageKey: "vanilla",
    allergens: "COCONUT, WHEAT, SOY, SULFITES",
  },
  "cake-cardamom-rose": {
    name: "Cardamom Rose Cake",
    category: "cake",
    tagline: "Three layers of cardamom-spiced cake with rose buttercream. The flavor people won't stop asking us to bring back.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, ROSE EXTRACT (ALCHOL, GLYCERIN, NATURAL FLAVORS), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), CARDAMOM POWDER, FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, RED 40, SODIUM BENZOATE (PRESERVATIVE), CITRIC ACID), BAKING SODA, SALT",
    sizeInfo: "Net weight: 84.66oz (2400g)",
    gfAvailable: true,
    imageKey: "rose",
    allergens: "WHEAT, SOY",
  },
  "cake-mango-vanilla": {
    name: "Mango Vanilla Cake",
    category: "cake",
    tagline: "Three vanilla layers filled with sweet mango. Bright, tropical, and it looks as good as the photos.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), MANGO PULP (MANGO PULP, WATER, SUGAR, CITRIC ACID) APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "mango",
    allergens: "WHEAT, SOY",
  },
  "cake-vanilla-spice": {
    name: "Vanilla Spice Cake",
    category: "cake",
    tagline: "Vanilla cake spiced with cinnamon, ginger, clove, and nutmeg. Warm and cozy. Good any time of year.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, CINNAMON, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), GINGER, BAKING SODA, CLOVE, NUTMEG SALT",
    sizeInfo: "Net weight: 84.66oz (2400g)",
    gfAvailable: true,
    imageKey: "vanilla",
    allergens: "WHEAT, SOY",
  },
  "cake-vanilla-lemon-curd": {
    name: "Vanilla with Lemon Curd Filling",
    category: "cake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "lemon",
    allergens: "",
  },
  "cake-strawberry-crunch": {
    name: "Strawberry Crunch Cake",
    category: "cake",
    tagline: "Vanilla sponge stuffed with tangy strawberry buttercream made from real freeze-dried strawberries, rolled in golden biscuit crumble. The strawberry flavor is aggressive in the best way, without being too sweet.",
    ingredients: "Soy milk (organic soybase (filtered water, whole organic soybeans), tricalcium phosphate, sea salt, organic flavors, gellan gum, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sugar, powdered sugar, enriched bleached flour (wheat flour, malted barley flour, niacin, iron, thiamine, riboflavin, folic acid), light corn syrup (corn syrup, salt, vanilla), vegan butter (oil blend (palm fruit, canola, soybean, flax, and olive), water, salt, natural flavor (plant derived from corn), soy protein, soy lecithin, lactic acid (non-dairy), annatto extract (color)), canola oil, shortening (soybean oil, fully hydrogenated palm oil, palm oil, mono and diglycerides, TBHQ and citric acid (antioxidants)), freeze dried strawberries, apple cider vinegar, vanilla extract (water, alcohol (35%), sugar, vanilla bean extractives), water, baking soda, salt.",
    sizeInfo: "3 layers, 7-inch diameter, serves 10\u201320 small slices; 8\u201310 large slices",
    gfAvailable: false,
    imageKey: "strawberry",
    allergens: "WHEAT, SOY"
  },
  "cake-vanilla-biscoff": {
    name: "Vanilla Biscoff Cake",
    category: "cake",
    tagline: "A Biscoff lover's dream — vanilla cake layered with cookie butter and speculoos crunch. Sweet, spiced, and dangerously good.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COOKIE BUTTER (SPECULOOS COOKIES (WHEAT FLOUR [WHEAT FLOUR, MALTED WHEAT FLOUR], CARAMELIZED SUGAR, VEGETABLE OIL BLEND [PALM OIL, CANOLA OIL, CITRIC ACID AND LEMON JUICE CONCENTRATE {TO PRESERVE}], CANE SUGAR, SOY FLOUR, INVERT SUGAR SYRUP, WHEAT GLUTEN, SODIUM BICARBONATE, CINNAMON, NUTMEG)), BISCOFF COOKIES (WHEAT FLOUR, SUGAR, VEGETABLE OILS (SOYBEAN OIL, SUNFLOWER OIL, CANOLA OIL, PALM OIL), BROWN SUGAR SYRUP, SODIUM BICARBONATE (LEAVENING), SOY FLOUR, SALT, CINNAMON), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 12.7oz (360g)",
    gfAvailable: false,
    imageKey: "biscoff",
    allergens: "WHEAT, SOY",
  },
  "cake-pandan-vanilla": {
    name: "Pandan Vanilla Cake",
    category: "cake",
    tagline: "Vibrant green pandan with creamy vanilla and sweet macapuno coconut. A Southeast Asian classic, veganized. One of the flavors people ask about the most.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, MACAPUNO (COCONUT SPORT, YOUNG COCONUT, SUGAR, WATER, SODIUM CARBOXYMETHYLCELLULOSE,SOLDIUM, METABISULFITE (AS PRESERVATIVE)), SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, PANDAN FLAVOURING (GLUCOSE SYRUP, SORBITOL SYRUP, ARTIFICAL PANDAN FLAVOR, PROPYLENE GLYCOL, COLORING (FD&C YELLOW #5), MODIFIED STARCH, ARTIFICIAL VANILLIN FLAVOR, COLORING (FD&C BLUE #1), ETHYL MALTOL), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 90oz (2551g)",
    gfAvailable: true,
    imageKey: "pandan",
    allergens: "WHEAT, SOY, COCONUT",
  },
  "cake-ube-vanilla": {
    name: "Ube Vanilla Cake",
    category: "cake",
    tagline: "Does this not look like a beautiful galaxy! The Ube cake is a mellow 3-layer beauty, filled with our smooth purple Ube buttercream. The flavor is light, but Ube is nonetheless very impressive!",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, MACAPUNO (COCONUT SPORT, YOUNG COCONUT, SUGAR, WATER, SODIUM CARBOXYMETHYLCELLULOSE,SOLDIUM, METABISULFITE (AS PRESERVATIVE)), SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, UBE FLAVOURING (GLUCOSE SYRUP, WATER, PROPYLENE GLYCOL, SORBITOL SYRUP, ARTIFICIAL SWEET POTATO FLAVOR, COLORING (FD&C RED #3 & FD&C BLUE #1), ETHYL VANILLA)), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 90oz (2551g)",
    gfAvailable: true,
    imageKey: "ube",
    // batch2 reasoning: macapuno is the classic ube pairing, no competing ube cake item
    allergens: "WHEAT, SOY, COCONUT",
  },
  "cake-white-forest": {
    name: "White Forest Cake",
    category: "cake",
    tagline: "Do you like chocolate cake? Vanilla cake? Cherries? Good, because this one has all three. Sweet and sour cherries balanced with vanilla and chocolate, plus chopped chocolate throughout. Our Forest series is one of our most popular for a reason.",
    ingredients: "Soy milk (organic soybase (filtered water, whole organic soybeans), tricalcium phosphate, sea salt, organic flavors, gellan gum, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sugar, powdered sugar (sugar, cornstarch), enriched bleached flour (wheat flour, malted barley flour, niacin, iron, thiamine, riboflavin, folic acid), light corn syrup (corn syrup, salt, vanilla), vegan butter (oil blend (palm fruit, canola, soybean, flax, and olive), water, salt, natural flavor (plant derived from corn), soy protein, soy lecithin, lactic acid (non-dairy), annatto extract (color)), canola oil, shortening (soybean oil, fully hydrogenated palm oil, palm oil, mono and diglycerides, TBHQ and citric acid (antioxidants)), cocoa, apple cider vinegar, strawberry syrup (high fructose corn syrup, corn syrup, water, artificial flavors, citric acid, sodium benzoate, xanthan gum, Red 40), vanilla extract (water, alcohol (35%), sugar, vanilla bean extractives), baking powder (sodium acid pyrophosphate, sodium bicarbonate, cornstarch, monocalcium phosphate), salt.",
    sizeInfo: "3 layers, 7-inch diameter, serves 10\u201320 small slices; 8\u201310 large slices",
    gfAvailable: true,
    imageKey: "whiteforest",
    allergens: "WHEAT, SOY"
  },
  "cake-gender-reveal-pink": {
    name: "Gender Reveal Cake (Pink)",
    category: "cake",
    tagline: "The big moment deserves a big cake. Vanilla layers hiding a pink surprise inside — cut into it and let the celebration begin!",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, COLORING (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, RED 40, SODIUM BENZOATE (PRESERVATIVE), CITRIC ACID), SALT",
    sizeInfo: "Net weight: 84.66oz (2400g)",
    gfAvailable: false,
    imageKey: "strawberry",
    allergens: "WHEAT, SOY",
  },
  "cake-gender-reveal-blue": {
    name: "Gender Reveal Cake (Blue)",
    category: "cake",
    tagline: "The suspense is real. A classic vanilla cake with a blue secret waiting inside — the sweetest way to share your news.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, COLORING (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, CARRAGEENAN, BLUE 1, BENZOATE (PRESERVATIVE), CITRIC ACID) SALT",
    sizeInfo: "Net weight: 84.66oz (2400g)",
    gfAvailable: false,
    imageKey: "blue",
    allergens: "WHEAT, SOY",
  },
  "cake-red-velvet": {
    name: "Red Velvet Cake",
    category: "cake",
    tagline: "It's a red velvet cake. That's all that needs to be said about this beauty.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA),VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, COCOA, RED GEL FOOD COLOR (SOFT GEL PASTE FOOD COLOR (WATER, SUGAR, US CERTIFIED RED 40 (E129), RED 3 (E127), YELLOW 6 (E110), MODIFIED CORN STARCH, VEGTABLE GUM, CITRIC ACID AND 1/10 OF SODIUM BENZONATE AND POTASSIUM SORBATE (AS PRESERVATIVES)), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT",
    sizeInfo: "Net weight: 84.66oz (2400g)",
    gfAvailable: true,
    imageKey: "redvelvet",
    allergens: "WHEAT, SOY",
  },
  "cake-custom-order": {
    name: "Custom Order Cake",
    category: "cake",
    tagline: "Got something specific in mind? We'll work with you to design a fully custom vegan cake. Pricing starts at $60 and depends on complexity. Details are limited by Washington's Cottage Food law — we'll discuss everything after you place your order.",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "custom",
    allergens: "",
  },

  /* ======================================================
     CUPCAKES — 22 items
     ====================================================== */
  "cupcake-almond-crunch": {
    name: "Almond Crunch",
    category: "cupcake",
    tagline: "A bite-sized version of our most popular cake. Smooth almond buttercream, crunchy roasted almonds. Simple and really good if you're into almonds.",
    ingredients: "VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE)), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR), SUGAR, SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), ALMONDS, POWDERED SUGAR, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), WATER, \\FLAXSEED, APPLE CIDER VINEGAR, ALMOND EXTRACT (WATER, ALCOHOL, OIL OF BITTER ALMOND), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT",
    sizeInfo: "Net weight: 44.45 oz (1260g)",
    gfAvailable: false,
    imageKey: "almond",
    allergens: "ALMOND, WHEAT, SOY",
  },
  "cupcake-chocolate-vanilla": {
    name: "Chocolate Vanilla",
    category: "cupcake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "chocolate",
    allergens: "",
  },
  "cupcake-chocolate-candy-cane": {
    name: "Chocolate Candy Cane",
    category: "cupcake",
    tagline: "A festive chocolate cupcake with a cool peppermint kick. Tastes like the holidays. We won't judge if you order it in July.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), SOFT GEL PASTE FOOD COLOR (WATER, SUGAR, US CERTIFIED RED 40 (E129), RED 3 (E127), YELLOW 6 (E110), MODIFIED CORN STARCH, VEGTABLE GUM, CITRIC ACID AND 1/10 OF SODIUM BENZONATE AND POTASSIUM SORBATE (AS PRESERVATIVES)) BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "Net weight: 38.8oz (1100g)",
    gfAvailable: true,
    imageKey: "candycane",
    allergens: "WHEAT, SOY",
  },
  "cupcake-chocolate-mint": {
    name: "Chocolate Mint",
    category: "cupcake",
    tagline: "A mint-chocolate cupcake. Cool, refreshing, and deeply chocolatey with green mint buttercream.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), GEL FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, YELLOW 5, CARRAGEENAN, BLUE 1, RED 40, SODIUM BENZOATE (PRESERVATIVE), CIRTRIC ACID, BAKING POWDER (CORN STARCH, SODIUM BICARBONATE, SODIUM ALUMINUM SULFATE, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "Net weight: 38.8oz (1100g)",
    gfAvailable: true,
    imageKey: "mint",
    allergens: "WHEAT, SOY",
  },
  "cupcake-chocolate-coffee": {
    name: "Chocolate Coffee",
    category: "cupcake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "coffee",
    allergens: "",
  },
  "cupcake-chocolate-oreo-crunch": {
    name: "Chocolate Oreo Crunch",
    category: "cupcake",
    tagline: "Everything you like about cookies and cream, packed into a cupcake with Oreo crunch in every bite.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, SEMISWEET CHOCOLATE CHIPS (CHOCOLATE LIQUOR, SUGAR, SOY LECITHIN, VANILLA), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, REDSODIUM BENZOATE (PRESERVATIVE), CITRIC ACID), BAKING POWDER (CORN STARCH, SODIUM BICARBONATE, SODIUM ALUMINUM SULFATE, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "Net weight: 33oz (1200g)",
    gfAvailable: false,
    imageKey: "oreo",
    allergens: "WHEAT, SOY",
  },
  "cupcake-chocolate-strawberry-crunch": {
    name: "Chocolate Strawberry Crunch",
    category: "cupcake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "strawberry",
    allergens: "",
  },
  "cupcake-chocolate-peanut-butter": {
    name: "Chocolate Peanut Butter",
    category: "cupcake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "peanut",
    allergens: "",
  },    "cupcake-black-forest": {
      name: "Black Forest",
      category: "cupcake",
      tagline: "",
      // ingredients copied from cake-black-forest per standing rule: same batter/frosting, different format
      ingredients: "Chocolate cake (enriched flour (wheat flour, niacin, reduced iron, thiamine, mononitrate, riboflavin, folic acid), organic sugar, water, organic soymilk (filtered water, organic soybeans, contains 2% or less of: vitamin and mineral blend (calcium carbonate, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sea salt, gellan gum, ascorbic acid (vitamin C to protect)), canola oil, cocoa (processed with alkali), instant coffee powder, baking powder, baking soda, vanilla extract (water, ethyl alcohol, vanilla extract)); buttercream (vegan butter (vegetable oil blend (palm oil, canola oil), water, salt, pea protein isolate, monoglycerides, diglycerides, sunflower lecithin, artificial flavors, vitamin A palmitate, beta carotene with potassium sorbate, lactic acid, and calcium disodium EDTA), shortening (canola oil, modified palm and palm kernel oils, mono and diglycerides), corn syrup (light corn syrup, salt, and vanilla), sugar, water, instant coffee powder, vanilla extract (water, ethyl alcohol, vanilla extract), chocolate shards (sugar, hydrogenated palm fat, cocoa, soy lecithin, flavorings), meringue mushrooms (aquafaba, organic sugar, vinegar, cocoa powder (processed with alkali), matcha powder)).",
      sizeInfo: "",
      gfAvailable: true,
      imageKey: "blackforest",
      allergens: "",
    },
  "cupcake-toasted-smores": {
    name: "Toasted S'mores Cupcakes",
    category: "cupcake",
    tagline: "A cookie cupcake base with torched meringue on top. You get the chocolate, the marshmallow, and the graham cracker vibes all at once. It's a s'more but make it a cupcake.",
    ingredients: "Chocolate cake (enriched flour (wheat flour, niacin, reduced iron, thiamine, mononitrate, riboflavin, folic acid), organic sugar, water, organic soymilk (filtered water, organic soybeans, contains 2% or less of: vitamin and mineral blend (calcium carbonate, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sea salt, gellan gum, ascorbic acid (vitamin C to protect)), canola oil, cocoa (processed with alkali), instant coffee powder, baking powder, baking soda, vanilla extract (water, ethyl alcohol, vanilla extract)); meringue (sugar, aquafaba, water, vinegar).",
    sizeInfo: "Sold in sets of 6 or 12",
    gfAvailable: false,
    imageKey: "smores",
    // inferred from ingredient list (not printed label)
    allergens: "",
  },
  "cupcake-vanilla-sprinkle": {
    name: "Vanilla Sprinkle",
    category: "cupcake",
    tagline: "The party cupcake — vanilla loaded with rainbow sprinkles inside and out. Simple, happy, and always the first to disappear from the box.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), RAINBOW SPRINKLES (SUGAR, HYDROGENATED PALM KERNEL OIL, CORN STARCH, SUNFLOWER LECITHIN, FD&C COLORS YELLOW 6 LAKE, YELLOW 5 LAKE, BLUE 1 LAKE, RED 40 LAKE, RED 3, MALTODEXTRIN, CARNAUBA WAX, VANILLIN, CELLULOSE GUM), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 42.33oz (1200g)",
    gfAvailable: true,
    imageKey: "vanilla",
    allergens: "WHEAT, SOY",
  },
  "cupcake-matcha": {
    name: "Matcha",
    category: "cupcake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "matcha",
    allergens: "",
  },
  "cupcake-cardamom-rose": {
    name: "Cardamom Rose",
    category: "cupcake",
    tagline: "A moist cupcake infused with rose, topped with rose buttercream. Floral, creamy, and not too sweet. People are weirdly obsessed with these — try one and you'll get it.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, ROSE EXTRACT (ALCHOL, GLYCERIN, NATURAL FLAVORS), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), CARDOMAM POWDER, FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, RED 40, SODIUM BENZOATE (PRESERVATIVE), CITRIC ACID), BAKING SODA, SALT",
    sizeInfo: "Net weight: 42.33oz (1200g)",
    gfAvailable: true,
    imageKey: "rose",
    allergens: "WHEAT, SOY",
  },
  "cupcake-mango-vanilla": {
    name: "Mango Vanilla",
    category: "cupcake",
    tagline: "Sweet mango and smooth vanilla buttercream. Tropical, bright, and balanced.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), MANGO PULP (MANGO PULP, WATER,SUGAR, CITRIC ACID) APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 42.33oz (1200g)",
    gfAvailable: true,
    imageKey: "mango",
    allergens: "WHEAT, SOY",
  },
  "cupcake-lemon-curd-vanilla": {
    name: "Lemon Curd Vanilla",
    category: "cupcake",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "lemon",
    allergens: "",
  },    "cupcake-strawberry-crunch": {
      name: "Strawberry Crunch",
      category: "cupcake",
      tagline: "",
      ingredients: "Soy milk (organic soybase (filtered water, whole organic soybeans), tricalcium phosphate, sea salt, organic flavors, gellan gum, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sugar, powdered sugar, enriched bleached flour (wheat flour, malted barley flour, niacin, iron, thiamine, riboflavin, folic acid), light corn syrup (corn syrup, salt, vanilla), vegan butter (oil blend (palm fruit, canola, soybean, flax, and olive), water, salt, natural flavor (plant derived from corn), soy protein, soy lecithin, lactic acid (non-dairy), annatto extract (color)), canola oil, shortening (soybean oil, fully hydrogenated palm oil, palm oil, mono and diglycerides, TBHQ and citric acid (antioxidants)), freeze dried strawberries, apple cider vinegar, vanilla extract (water, alcohol (35%), sugar, vanilla bean extractives), water, baking soda, salt.",
      sizeInfo: "",
      gfAvailable: false,
      imageKey: "strawberry",
      allergens: "WHEAT, SOY",
    },
  "cupcake-vanilla-biscoff": {
    name: "Vanilla Biscoff",
    category: "cupcake",
    tagline: "Cookie butter meets vanilla cupcake — spiced speculoos magic in every bite. If you know, you know.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COOKIE BUTTER (SPECULOOS COOKIES (WHEAT FLOUR [WHEAT FLOUR, MALTED WHEAT FLOUR], CARAMELIZED SUGAR, VEGETABLE OIL BLEND [PALM OIL, CANOLA OIL, CITRIC ACID AND LEMON JUICE CONCENTRATE {TO PRESERVE}], CANE SUGAR, SOY FLOUR, INVERT SUGAR SYRUP, WHEAT GLUTEN, SODIUM BICARBONATE, CINNAMON, NUTMEG)), BISCOFF COOKIES (WHEAT FLOUR, SUGAR, VEGETABLE OILS (SOYBEAN OIL, SUNFLOWER OIL, CANOLA OIL, PALM OIL), BROWN SUGAR SYRUP, SODIUM BICARBONATE (LEAVENING), SOY FLOUR, SALT, CINNAMON), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 44.45oz (1260g)",
    gfAvailable: false,
    imageKey: "biscoff",
    allergens: "WHEAT, SOY",
  },
  "cupcake-pandan-vanilla": {
    name: "Pandan Vanilla",
    category: "cupcake",
    tagline: "The flavor of pandan and the sweetness of macapuno coconut, in one beautiful green cupcake — the one people can't stop asking about.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, MACAPUNO (COCONUT SPORT, YOUNG COCONUT, SUGAR, WATER, SODIUM CARBOXYMETHYLCELLULOSE,SOLDIUM, METABISULFITE (AS PRESERVATIVE)), SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, PANDAN FLAVOURING (GLUCOSE SYRUP, SORBITOL SYRUP, ARTIFICAL PANDAN FLAVOR, PROPYLENE GLYCOL, COLORING (FD&C YELLOW #5), MODIFIED STARCH, ARTIFICIAL VANILLIN FLAVOR, COLORING (FD&C BLUE #1), ETHYL MALTOL), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 44.45oz (1260g)",
    gfAvailable: true,
    imageKey: "pandan",
    allergens: "WHEAT, SOY, COCONUT",
  },
  "cupcake-ube-vanilla": {
    name: "Ube Vanilla",
    category: "cupcake",
    tagline: "Vibrant purple ube with smooth vanilla buttercream. The color stops the scroll every single time.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, MACAPUNO (COCONUT SPORT, YOUNG COCONUT, SUGAR, WATER, SODIUM CARBOXYMETHYLCELLULOSE,SOLDIUM, METABISULFITE (AS PRESERVATIVE)), SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, UBE FLAVOURING (GLUCOSE SYRUP, WATER, PROPYLENE GLYCOL, SORBITOL SYRUP, ARTIFICIAL SWEET POTATO FLAVOR, COLORING (FD&C RED #3 & FD&C BLUE #1), ETHYL VANILLA)), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 44.45oz (1260g)",
    gfAvailable: true,
    imageKey: "ube",
    allergens: "WHEAT, SOY, COCONUT",
  },
  "cupcake-milk-tea-boba": {
    name: "Milk Tea Boba",
    category: "cupcake",
    tagline: "Your favorite boba shop order, but make it a cupcake — black tea-infused cake topped with chewy tapioca pearls. Yes, really. And yes, it's as good as it sounds.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), WATER, BROWN SUGAR, TAPIOCA STARCH, MODIFIED TAPIOCA STARCH, CARAMEL COLOR, NATURAL FLAVOR, SODIUM CARBOXYMETHYLCELLULOSE, APPLE CIDER VINEGAR, BLACK TEA POWDER, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 50.76oz (1020g)",
    gfAvailable: false,
    imageKey: "milktea",
    allergens: "WHEAT, SOY",
  },
  "cupcake-red-velvet": {
    name: "Red Velvet",
    category: "cupcake",
    tagline: "A classic red velvet cupcake — deep crimson, hint of cocoa, and that signature tang. Sometimes the classics just work, no explanation needed.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA),VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON- DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, COCOA, RED GEL FOOD COLOR (SOFT GEL PASTE FOOD COLOR (WATER, SUGAR, US CERTIFIED RED 40 (E129), RED 3 (E127), YELLOW 6 (E110), MODIFIED CORN STARCH, VEGTABLE GUM, CITRIC ACID AND 1/10 OF SODIUM BENZONATE AND POTASSIUM SORBATE (AS PRESERVATIVES)), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT",
    sizeInfo: "Net weight: 42.33oz (1200g)",
    gfAvailable: false,
    imageKey: "redvelvet",
    allergens: "WHEAT, SOY",
  },
  "cupcake-vanilla-chocolate-swirl": {
    name: "Vanilla Chocolate Swirl",
    category: "cupcake",
    tagline: "Vanilla and chocolate swirled together in one cupcake. Moist, fluffy, and simple. If you can't decide between vanilla and chocolate, you don't have to.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, SOYBEAN, CANOLA, VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)) CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT",
    sizeInfo: "Net weight: 38.8 oz (1110g)",
    gfAvailable: true,
    imageKey: "swirl",
    allergens: "WHEAT, SOY",
  },
  /* ======================================================
     COOKIES — 8 items
     ====================================================== */
  "cookie-biscoff-stuff": {
    name: "Biscoff Stuff",
    category: "cookie",
    tagline: "A GIANT cookie stuffed with Biscoff spread and speculoos crumble — spiced, sweet, and absolutely loaded. We're not kidding about the GIANT part.",
    ingredients: "ENRICHED UNBLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID),VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)) BROWN SUGAR, SUGAR, MAPLE SYRUP, SPECCULOUS COOKIES (WHEAT FLOUR, SUGAR, VEGETABLE OILS (SOY BEAN OIL, SUNFLOWER OIL, CANOLA OIL, PALM OIL), BROWN SUGAR, SODIUM BICARBONATE (LEAVENING), SOY FLOUR, SALT, CINNAMON), COOKIE BUTTER (SPECULOOS COOKIES (WHEAT FLOUR [WHEAT FLOUR, MALTED WHEAT FLOUR], CARAMELIZED SUGAR, VEGETABLE OIL BLEND [PALM OIL, CANOLA OIL, CITRIC ACID AND LEMON JUICE CONCENTRATE {TO PRESERVE}], CANE SUGAR, SOY FLOUR, INVERT SUGAR SYRUP, WHEAT GLUTEN, SODIUM BICARBONATE, CINNAMON, NUTMEG) VEGETABLE OIL BLEND (CANOLA OIL, PALM OIL, CITRIC ACID [TO PRESERVE]) SUGAR CANOLA LECITHIN), FLAXSEED, CINNAMON, BAKING SODA, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), SALT, GROUND GINGER, NUTMEG, CLOVES",
    sizeInfo: "Net weight: 30oz (840g)",
    gfAvailable: false,
    imageKey: "biscoff",
    allergens: "WHEAT, SOY",
  },
  "cookie-blue-monster": {
    name: "Blue Cookie Monster",
    category: "cookie",
    tagline: "A bright blue GIANT cookie packed with Oreos, chocolate chips, and Biscoff crumbs. Cookie Monster would approve.",
    ingredients: "ENRICHED UNBLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), BROWN SUGAR, SUGAR, OREOS (SUGAR, UNBLEACHED ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE {VITAMIN B1}, RIBOFLAVIN {VITAMIN B2}, FOLIC ACID), PALM AND/OR CANOLA OIL, COCOA (PROCESSED WITH ALKALI), HIGH FRUCTOSE CORN SYRUP, CORNSTARCH, LEAVENING (BAKING SODA AND/OR CALCIUM PHOSPHATE), SALT, SOY LECITHIN, VANILLIN - AN ARTIFICIAL FLAVOR, CHOCOLATE), SEMI-SWEET CHOCOLATE CHIPS (CHOCOLATE LIQUOR, SUGAR, SOY LECITHIN, VANILLA), BISCOFF COOKIES (WHEAT FLOUR, SUGAR, VEGETABLE OILS (SOYBEAN OIL, SUNFLOWER OIL, CANOLA OIL, PALM OIL), BROWN SUGAR SYRUP, SODIUM BICARBONATE, SOY FLOUR, SALT, CINNAMON), FLAXSEED, BAKING SODA, SALT, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), ARTIFICAL COLORING (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, CARRAGEENAN, BLUE 1, BENZOATE [PRESERVATIVE], CITRIC ACID)",
    sizeInfo: "Net weight: 30oz (840g)",
    gfAvailable: false,
    imageKey: "blue",
    allergens: "WHEAT, SOY",
  },
  "cookie-ube": {
    name: "Ube",
    category: "cookie",
    tagline: "A vibrant purple GIANT ube cookie loaded with Oreos. The color gets people's attention but the taste is what makes them order it again.",
    ingredients: "ENRICHED UNBLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), VEGAN BUTTER (OIL BLEND (PALM FRUIT, SOYBEAN, CANOLA, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), BROWN SUGAR, SUGAR, OREOS (SUGAR, UNBLEACHED ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE {VITAMIN B1}, RIBOFLAVIN {VITAMIN B2}, FOLIC ACID), PALM AND/OR CANOLA OIL, HIGH FRUCTOSE CORN SYRUP, CORNSTARCH, LEAVENING (BAKING SODA AND/OR CALCIUM PHOSPHATE), SALT, SOY LECITHIN, VANILLIN - AN ARTIFICIAL FLAVOR, CHOCOLATE), BROWN SUGAR SYRUP, SODIUM BICARBONATE, SOY FLOUR, SALT, CINNAMON), FLAXSEED, BAKING SODA, SALT, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), UBE FLAVOURING (GLUCOSE SYRUP, WATER, PROPYLENE GLYCOL, SORBITOL SYRUP, ARTIFICIAL SWEET POTATO FLAVOR, COLORING (FD&C RED #3 & FD&CBLUE #1), ETHYL VANILLA))",
    sizeInfo: "Net weight: 30oz (840g)",
    gfAvailable: true,
    imageKey: "ube",
    allergens: "WHEAT, SOY",
  },
  "cookie-party-sprinkles": {
    name: "Party Sprinkles",
    category: "cookie",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "sprinkle",
    allergens: "",
  },
  "cookie-toasted-smores": {
    name: "Toasted S'mores",
    category: "cookie",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "smores",
    allergens: "",
  },
  "cookie-chocolate-chip": {
    name: "Chocolate Chip",
    category: "cookie",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "chocolate",
    allergens: "",
  },
  "cookie-pumpkin-spice-latte": {
    name: "Pumpkin Spice Latte",
    category: "cookie",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "pumpkin",
    allergens: "",
  },
  "cookie-strawberry-crunch": {
    name: "Strawberry Crunch",
    category: "cookie",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "strawberry",
    allergens: "",
  },

  /* ======================================================
     CAKE POPS — 5 items
     ====================================================== */
  "cakepop-red-velvet": {
    name: "Red Velvet (White Chocolate)",
    category: "cakepop",
    tagline: "Red velvet cake dipped in white chocolate on a stick. Bite-sized, and it's actually hard to eat just one.",
    ingredients: "NONDAIRY WHITE CHOCOLATE COINS (SUGAR, HYDROGENATED PALM FAT, MALTODEXTRINE, EMULSIFIERS (SOY LECITHIN, POLYGLYCEROL POLYRICONEATE), FLAVORINGS, SALT, FOOD COLORINGS ( TITANIUM DIOXIDE)), SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA),VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, COCOA, RED GEL FOOD COLOR (SOFT GEL PASTE FOOD COLOR (WATER, SUGAR, US CERTIFIED RED 40 (E129), RED 3 (E127), YELLOW 6 (E110), MODIFIED CORN STARCH, VEGTABLE GUM, CITRIC ACID AND 1/10 OF SODIUM BENZONATE AND POTASSIUM SORBATE (AS PRESERVATIVES)), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT",
    sizeInfo: "Net weight: 16.93oz (480g)",
    gfAvailable: false,
    imageKey: "redvelvet",
    allergens: "WHEAT, SOY",
  },
  "cakepop-double-dough-biscoff": {
    name: "Double Dough Biscoff (White Chocolate)",
    category: "cakepop",
    tagline: "Cookie dough meets Biscoff meets white chocolate. On a stick.",
    ingredients: "SEMISWEET CHOCOLATE CHIPS (CHOCOLATE LIQUOR, SUGAR, SOY LECITHIN, VANILLA), SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), CANOLA OIL, POWDERED SUGAR, LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), CARABUNA WAX), COOKIE BUTTER (SPECULOOS COOKIES (WHEAT FLOUR [WHEAT FLOUR, MALTED WHEAT FLOUR], CARAMELIZED SUGAR, VEGETABLE OIL BLEND [PALM OIL, CANOLA OIL, CITRIC ACID AND LEMON JUICE CONCENTRATE {TO PRESERVE}], APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "Net weight: 16.93oz (480g)",
    gfAvailable: false,
    imageKey: "dough",
    allergens: "WHEAT, SOY",
  },
  "cakepop-chocolate-lovers": {
    name: "Chocolate Lovers (White Chocolate)",
    category: "cakepop",
    tagline: "Double chocolate cake pops dipped in smooth white chocolate — for when you need a little chocolate... times two. On a stick.",
    ingredients: "SEMISWEET CHOCOLATE CHIPS (CHOCOLATE LIQUOR, SUGAR, SOY LECITHIN, VANILLA), ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE, MONONITRATE, RIBOFLAVIN, FOLIC ACID, ORGANIC SUGAR, WATER, SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), VITAMIN AND MINERAL BLEND (CALCIUM CARBONATE, VITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN [B2], VITAMIN B12), SEA SALT, GELLAN GUM, ASCORBIC ACID (VITAMIN C TO PROTECT)), CANOLA OIL, COCOA (PROCESSED WITH ALKALI), INSTANT COFFEE POWDER, BAKING POWDER, BAKING SODA, VANILLA EXTRACT (WATER, ETHYL ALCOHOL, VANILLA EXTRACT)",
    sizeInfo: "Net weight: 16.93oz (480g)",
    gfAvailable: true,
    imageKey: "chocolate",
    allergens: "WHEAT, SOY",
  },
  /* TODO: confirm with client — tagline, ingredients, sizeInfo, allergens and the
     coating name for the two pops below. Deliberately left blank rather than
     copied from another flavor: allergen text must come from the client. */
  "cakepop-double-dough": {
    name: "Double Dough",
    category: "cakepop",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "dough",
    allergens: "",
  },
  "cakepop-zebra": {
    name: "Zebra",
    category: "cakepop",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "zebra",
    allergens: "",
  },

  /* ======================================================
     CAKE JARS — 21 items (same as cupcake flavors, except Toasted Smores)
     ====================================================== */
  "cakejar-almond-crunch": {
    name: "Almond Crunch",
    category: "cakejar",
    tagline: "All the almond-crunch goodness of our signature cake, layered in a portable jar. For almond lovers who want their fix in single-serve form.",
    ingredients: "VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE)), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR), SUGAR, SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), ALMONDS, POWDERED SUGAR, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), WATER, \\FLAXSEED, APPLE CIDER VINEGAR, ALMOND EXTRACT (WATER, ALCOHOL, OIL OF BITTER ALMOND), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "almond",
    allergens: "ALMOND, WHEAT, SOY",
  },
  "cakejar-chocolate-vanilla": {
    name: "Chocolate Vanilla",
    category: "cakejar",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "chocolate",
    allergens: "",
  },
  "cakejar-chocolate-candy-cane": {
    name: "Chocolate Candy Cane",
    category: "cakejar",
    tagline: "Chocolate peppermint in a jar. Holiday vibes in every spoonful, available year-round.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), SOFT GEL PASTE FOOD COLOR (WATER, SUGAR, US CERTIFIED RED 40 (E129), RED 3 (E127), YELLOW 6 (E110), MODIFIED CORN STARCH, VEGTABLE GUM, CITRIC ACID AND 1/10 OF SODIUM BENZONATE AND POTASSIUM SORBATE (AS PRESERVATIVES)) BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "candycane",
    allergens: "WHEAT, SOY",
  },
  "cakejar-chocolate-mint": {
    name: "Chocolate Mint",
    category: "cakejar",
    tagline: "Mint chocolate in a jar. Cool, refreshing, and really easy to finish in one sitting.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), GEL FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, YELLOW 5, CARRAGEENAN, BLUE 1, RED 40, SODIUM BENZOATE (PRESERVATIVE), CIRTRIC ACID, BAKING POWDER (CORN STARCH, SODIUM BICARBONATE, SODIUM ALUMINUM SULFATE, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "mint",
    allergens: "WHEAT, SOY",
  },
  "cakejar-chocolate-coffee": {
    name: "Chocolate Coffee",
    category: "cakejar",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "coffee",
    allergens: "",
  },
  "cakejar-chocolate-oreo-crunch": {
    name: "Chocolate Oreo Crunch",
    category: "cakejar",
    tagline: "Oreo crunch cake in a jar. Cookies and cream in every spoonful.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, SEMISWEET CHOCOLATE CHIPS (CHOCOLATE LIQUOR, SUGAR, SOY LECITHIN, VANILLA), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), PEPPERMINT EXTRACT (ALCOHOL, PEPPERMINT OIL), FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, REDSODIUM BENZOATE (PRESERVATIVE), CITRIC ACID), BAKING POWDER (CORN STARCH, SODIUM BICARBONATE, SODIUM ALUMINUM SULFATE, MONOCALCIUM PHOSPHATE), SALT,",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "oreo",
    allergens: "WHEAT, SOY",
  },
  "cakejar-chocolate-strawberry-crunch": {
    name: "Chocolate Strawberry Crunch",
    category: "cakejar",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "strawberry",
    allergens: "",
  },
  "cakejar-chocolate-peanut-butter": {
    name: "Chocolate Peanut Butter",
    category: "cakejar",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "peanut",
    allergens: "",
  },
  "cakejar-black-forest": {
    name: "Black Forest",
    category: "cakejar",
    tagline: "Our chocolate-and-cherry forest cake, jarred for one. All the layers, none of the slicing.",
    ingredients: "Chocolate cake (enriched flour (wheat flour, niacin, reduced iron, thiamine, mononitrate, riboflavin, folic acid), organic sugar, water, organic soymilk (filtered water, organic soybeans, contains 2% or less of: vitamin and mineral blend (calcium carbonate, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sea salt, gellan gum, ascorbic acid (vitamin C to protect)), canola oil, cocoa (processed with alkali), instant coffee powder, baking powder, baking soda, vanilla extract (water, ethyl alcohol, vanilla extract)); buttercream (vegan butter (vegetable oil blend (palm oil, canola oil), water, salt, pea protein isolate, monoglycerides, diglycerides, sunflower lecithin, artificial flavors, vitamin A palmitate, beta carotene with potassium sorbate, lactic acid, and calcium disodium EDTA), shortening (canola oil, modified palm and palm kernel oils, mono and diglycerides), corn syrup (light corn syrup, salt, and vanilla), sugar, water, instant coffee powder, vanilla extract (water, ethyl alcohol, vanilla extract), chocolate shards (sugar, hydrogenated palm fat, cocoa, soy lecithin, flavorings), meringue mushrooms (aquafaba, organic sugar, vinegar, cocoa powder (processed with alkali), matcha powder)).",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "blackforest",
    allergens: "",
  },
  "cakejar-vanilla-sprinkle": {
    name: "Vanilla Sprinkle",
    category: "cakejar",
    tagline: "Vanilla sprinkle cake in a jar. Colorful, fun, and good for celebrations. Or a random Tuesday.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), RAINBOW SPRINKLES (SUGAR, HYDROGENATED PALM KERNEL OIL, CORN STARCH, SUNFLOWER LECITHIN, FD&C COLORS YELLOW 6 LAKE, YELLOW 5 LAKE, BLUE 1 LAKE, RED 40 LAKE, RED 3, MALTODEXTRIN, CARNAUBA WAX, VANILLIN, CELLULOSE GUM), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "vanilla",
    allergens: "WHEAT, SOY",
  },
  "cakejar-matcha": {
    name: "Matcha",
    category: "cakejar",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "matcha",
    allergens: "",
  },
  "cakejar-cardamom-rose": {
    name: "Cardamom Rose",
    category: "cakejar",
    tagline: "Cardamom rose cake, layered in a jar. All the floral, spiced flavor without having to cut a slice.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, ROSE EXTRACT (ALCHOL, GLYCERIN, NATURAL FLAVORS), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), CARDOMAM POWDER, FOOD COLOR (CORN SYRUP, SUGAR, WATER, MODIFIED CORNSTARCH, RED 40, SODIUM BENZOATE (PRESERVATIVE), CITRIC ACID), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "rose",
    allergens: "WHEAT, SOY",
  },
  "cakejar-mango-vanilla": {
    name: "Mango Vanilla",
    category: "cakejar",
    tagline: "Mango and vanilla layered in a jar. Bright, tropical, and ready when the craving hits.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), MANGO PULP (MANGO PULP, WATER,SUGAR, CITRIC ACID) APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "mango",
    allergens: "WHEAT, SOY",
  },
  "cakejar-lemon-curd-vanilla": {
    name: "Lemon Curd Vanilla",
    category: "cakejar",
    tagline: "",
    ingredients: "",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "lemon",
    allergens: "",
  },
  "cakejar-strawberry-crunch": {
    name: "Strawberry Crunch",
    category: "cakejar",
    tagline: "Strawberry crunch in a jar. That signature tangy strawberry flavor (still aggressive, still the best part) and golden crunch, now portable.",
    ingredients: "Soy milk (organic soybase (filtered water, whole organic soybeans), tricalcium phosphate, sea salt, organic flavors, gellan gum, vitamin A palmitate, vitamin D2, riboflavin (B2), vitamin B12), sugar, powdered sugar, enriched bleached flour (wheat flour, malted barley flour, niacin, iron, thiamine, riboflavin, folic acid), light corn syrup (corn syrup, salt, vanilla), vegan butter (oil blend (palm fruit, canola, soybean, flax, and olive), water, salt, natural flavor (plant derived from corn), soy protein, soy lecithin, lactic acid (non-dairy), annatto extract (color)), canola oil, shortening (soybean oil, fully hydrogenated palm oil, palm oil, mono and diglycerides, TBHQ and citric acid (antioxidants)), freeze dried strawberries, apple cider vinegar, vanilla extract (water, alcohol (35%), sugar, vanilla bean extractives), water, baking soda, salt.",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "strawberry",
    allergens: "WHEAT, SOY",
  },
  "cakejar-vanilla-biscoff": {
    name: "Vanilla Biscoff",
    category: "cakejar",
    tagline: "Vanilla cake with cookie butter and speculoos crunch, in a jar. Spoon-ready.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COOKIE BUTTER (SPECULOOS COOKIES (WHEAT FLOUR [WHEAT FLOUR, MALTED WHEAT FLOUR], CARAMELIZED SUGAR, VEGETABLE OIL BLEND [PALM OIL, CANOLA OIL, CITRIC ACID AND LEMON JUICE CONCENTRATE {TO PRESERVE}], CANE SUGAR, SOY FLOUR, INVERT SUGAR SYRUP, WHEAT GLUTEN, SODIUM BICARBONATE, CINNAMON, NUTMEG)), BISCOFF COOKIES (WHEAT FLOUR, SUGAR, VEGETABLE OILS (SOYBEAN OIL, SUNFLOWER OIL, CANOLA OIL, PALM OIL), BROWN SUGAR SYRUP, SODIUM BICARBONATE (LEAVENING), SOY FLOUR, SALT, CINNAMON), APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "biscoff",
    allergens: "WHEAT, SOY",
  },
  "cakejar-pandan-vanilla": {
    name: "Pandan Vanilla",
    category: "cakejar",
    tagline: "Pandan and macapuno coconut layered in a jar. A taste of the tropics, ready when you are.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, MACAPUNO (COCONUT SPORT, YOUNG COCONUT, SUGAR, WATER, SODIUM CARBOXYMETHYLCELLULOSE,SOLDIUM, METABISULFITE (AS PRESERVATIVE)), SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, PANDAN FLAVOURING (GLUCOSE SYRUP, SORBITOL SYRUP, ARTIFICAL PANDAN FLAVOR, PROPYLENE GLYCOL, COLORING (FD&C YELLOW #5), MODIFIED STARCH, ARTIFICIAL VANILLIN FLAVOR, COLORING (FD&C BLUE #1), ETHYL MALTOL), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "pandan",
    allergens: "WHEAT, SOY, COCONUT",
  },
  "cakejar-ube-vanilla": {
    name: "Ube Vanilla",
    category: "cakejar",
    tagline: "Ube vanilla in a jar. Purple, pretty, and portable.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, MACAPUNO (COCONUT SPORT, YOUNG COCONUT, SUGAR, WATER, SODIUM CARBOXYMETHYLCELLULOSE,SOLDIUM, METABISULFITE (AS PRESERVATIVE)), SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, UBE FLAVOURING (GLUCOSE SYRUP, WATER, PROPYLENE GLYCOL, SORBITOL SYRUP, ARTIFICIAL SWEET POTATO FLAVOR, COLORING (FD&C RED #3 & FD&C BLUE #1), ETHYL VANILLA)), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "ube",
    allergens: "WHEAT, SOY, COCONUT",
  },
  "cakejar-milk-tea-boba": {
    name: "Milk Tea Boba",
    category: "cakejar",
    tagline: "Milk tea boba in dessert form. Tea, brown sugar, and chewy pearls, in a jar.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR, ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), WATER, BROWN SUGAR, TAPIOCA STARCH, MODIFIED TAPIOCA STARCH, CARAMEL COLOR, NATURAL FLAVOR, SODIUM CARBOXYMETHYLCELLULOSE, APPLE CIDER VINEGAR, BLACK TEA POWDER, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING SODA, SALT",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "milktea",
    allergens: "WHEAT, SOY",
  },
  "cakejar-red-velvet": {
    name: "Red Velvet",
    category: "cakejar",
    tagline: "Red velvet in a jar. Same classic, now portable.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA),VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON- DAIRY), ANNATTO EXTRACT (COLOR)), CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), APPLE CIDER VINEGAR, COCOA, RED GEL FOOD COLOR (SOFT GEL PASTE FOOD COLOR (WATER, SUGAR, US CERTIFIED RED 40 (E129), RED 3 (E127), YELLOW 6 (E110), MODIFIED CORN STARCH, VEGTABLE GUM, CITRIC ACID AND 1/10 OF SODIUM BENZONATE AND POTASSIUM SORBATE (AS PRESERVATIVES)), VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT",
    sizeInfo: "",
    gfAvailable: false,
    imageKey: "redvelvet",
    allergens: "WHEAT, SOY",
  },
  "cakejar-vanilla-chocolate-swirl": {
    name: "Vanilla Chocolate Swirl",
    category: "cakejar",
    tagline: "Vanilla and chocolate swirled together in a jar. For when you can't pick just one.",
    ingredients: "SOY MILK (ORGANIC SOYBASE (FILTERED WATER, WHOLE ORGANIC SOYBEANS), TRICALCIUM PHOSPHATE, SEA SALT, ORGANIC FLAVORS, GELLAN GUM, BITAMIN A PALMITATE, VITAMIN D2, RIBOFLAVIN (B2), VITAMIN B12), SUGAR, POWDERED SUGAR (SUGAR, CORNSTARCH), ENRICHED BLEACHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE, RIBOFLAVIN, FOLIC ACID), LIGHT CORN SYRUP (CORN SYRUP, SALT, VANILLA), VEGAN BUTTER (OIL BLEND (PALM FRUIT, SOYBEAN, CANOLA, VEGAN BUTTER (OIL BLEND (PALM FRUIT, CANOLA, SOYBEAN, FLAX, AND OLIVE), WATER, SALT, NATURAL FLAVOR (PLANT DERIVED FROM CORN), SOY PROTEIN, SOY LECITHIN, LACTIC ACID (NON-DAIRY), ANNATTO EXTRACT (COLOR)) CANOLA OIL, SHORTENING (SOYBEAN OIL, FULLY HYDROGENATED PALM OIL, PALM OIL, MONO AND DIGLYCERIDES, TBHQ AND CITRIC ACID (ANTIOXIDANTS)), COCOA, APPLE CIDER VINEGAR, VANILLA EXTRACT (WATER, ALCOHOL (35%), SUGAR, VANILLA BEAN EXTRACTIVES), BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORNSTARCH, MONOCALCIUM PHOSPHATE), SALT",
    sizeInfo: "",
    gfAvailable: true,
    imageKey: "swirl",
    allergens: "WHEAT, SOY",
  },
};
